# Generated by Django 4.1.7 on 2023-03-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siloam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='loaction',
            new_name='location',
        ),
    ]
