# Generated by Django 4.1.7 on 2023-03-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siloam', '0003_alter_attendee_accomodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='QR_CODE/'),
        ),
    ]
