# Generated by Django 4.1.7 on 2023-03-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siloam', '0004_attendee_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='qr_code',
        ),
    ]
