# Generated by Django 4.1.7 on 2023-03-13 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siloam', '0005_remove_attendee_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now=True)),
                ('accomodation', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('transport', models.BooleanField(default=False)),
                ('time_out', models.DateTimeField(null=True)),
                ('attendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siloam.attendee')),
            ],
        ),
    ]
